---
# Java Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-service
  namespace: demo
spec:
  selector:
    matchLabels:
      app: java-service
  replicas: 1
  template:
    metadata:
      labels:
        app: java-service
    spec:
      containers:
      - name: java-service
        image: localhost:30500/demo-java-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: JAVA_OPTS
          value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Xms128m -Xmx384m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 20
---
# Java Service Service
apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: demo
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: java-service 