apiVersion: v1
kind: ConfigMap
metadata:
  name: insecure-registry-config
  namespace: kube-system
data:
  registries.yaml: |
    mirrors:
      "registry.registry.svc.cluster.local:5000":
        endpoint:
          - "http://registry.registry.svc.cluster.local:5000"
    configs:
      "registry.registry.svc.cluster.local:5000":
        tls:
          insecure_skip_verify: true 