apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: java-network-delay
  namespace: demo
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      app: java-service
  delay:
    latency: '200ms'
    correlation: '25'
    jitter: '50ms'
  duration: '5m' 