apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: java-return-injection
  namespace: demo
spec:
  action: return
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      app: java-service
  return:
    value: "null"
    methods:
      - name: "health"
        declaringClass: "com.demo.chaos.controller.ChaosController"
  duration: '30s' 