apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: java-exception-injection
  namespace: demo
spec:
  action: exception
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      app: java-service
  exception:
    class: "java.lang.OutOfMemoryError"
    methods:
      - name: ".*"
        declaringClass: "com.demo.chaos.controller.ChaosController"
  duration: '30s' 