apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: java-gc-injection
  namespace: demo
spec:
  action: gc
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      app: java-service
  duration: '30s' 