apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
  namespace: demo
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      app: web-service
  direction: both
  target:
    selector:
      namespaces:
        - demo
      labelSelectors:
        app: redis
  duration: '3m' 