apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-emulation
  namespace: demo
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      app: web-service
  delay:
    latency: '200ms'
    correlation: '25'
    jitter: '50ms'
  duration: '5m' 